version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.11.0-python3.12
    depends_on:
      - postgres
      - redis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./configs:/opt/airflow/configs
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    env_file:
      - .dev.env
    command: webserver
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.11.0-python3.12
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./configs:/opt/airflow/configs
      - ./logs:/opt/airflow/logs
    env_file:
      - .dev.env
    command: scheduler
    restart: unless-stopped

  airflow-worker:
    image: apache/airflow:2.11.0-python3.12
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./configs:/opt/airflow/configs
      - ./logs:/opt/airflow/logs
    env_file:
      - .dev.env
    command: celery worker
    restart: unless-stopped

volumes:
  postgres_data:
