version: '3'

services:
  airflow-worker:
    image: apache/airflow:2.11.0-python3.12
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./configs:/opt/airflow/configs
      - ./logs:/opt/airflow/logs
    env_file:
      - .worker.env
    networks:
      - airflow_net
    command: celery worker
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  airflow_net:
    external: true 