version: '3'

services:
  postgres:
    image: postgres:13
    env_file:
      - .db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - airflow_net
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:alpine
    env_file:
      - .db.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - airflow_net
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  airflow_net:
    name: airflow_net
    external: true 