name: Airflow CI / CD Pipeline

on:
  push:
    branches: 
      - main
      - feat/github_actions
  pull_request:
    branches: 
      - main
      - feat/github_actions

jobs:
  ci:
    name: Run Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 Lint
        run: flake8 .

      - name: Run Unit Tests
        run: |
          PYTHONPATH=plugins python -m unittest discover -s tests -p "test_*.py"
  cd:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Stop Scheduler on Webserver/Scheduler (Server A)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_A_USER }}@${{ secrets.SERVER_A_HOST }} << 'EOF'
            cd ~/dev-curation-airflow/
            echo "Stopping Airflow Scheduler..."
            sudo docker-compose -f docker-compose.airflow-main.yml stop airflow-scheduler
          EOF
      - name: Deploy to Worker (Server B)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_B_USER }}@${{ secrets.SERVER_B_HOST }} << 'EOF'
            cd ~/dev-curation-airflow/
            echo "Stopping Airflow Worker..."
            sudo docker-compose -f docker-compose.airflow-worker.yml stop airflow-worker
            echo "Updating Worker and Restarting..."
            git checkout main
            git pull origin main
            sudo docker-compose -f docker-compose.airflow-worker.yml up -d --build
          EOF
      - name: Deploy to Webserver/Scheduler (Server A)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_A_USER }}@${{ secrets.SERVER_A_HOST }} << 'EOF'
            cd ~/dev-curation-airflow/
            echo "Updating Webserver/Scheduler..."
            git checkout main
            git pull origin main
            sudo docker-compose -f docker-compose.airflow-main.yml down
            sudo docker-compose -f docker-compose.airflow-main.yml up -d --build
          EOF
